[supervisord]
nodaemon=true
user=root

[program:adguard]
command=/opt/adguardhome/AdGuardHome -c /opt/adguardhome/AdGuardHome.yaml -w /opt/adguardhome
autostart=true
autorestart=true
stdout_logfile=/var/log/adguard.log
stderr_logfile=/var/log/adguard.err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err.log
